config/routes.rb
get '/users/imports/new', :to => 'user_imports#new', :as => 'new_user_imports'
get '/imports', :to => 'imports#index', :defaults => { :type => 'UserImport' }, :as => 'all_user_imports'

app/controllers/user_imports_controller.rb
require 'csv'

class UserImportsController < ApplicationController
  include RedmineAdminActivity::Journalizable if Redmine::Plugin.installed?(:redmine_admin_activity)
  menu_item :users

  before_action :find_import, :only => [:show, :settings, :mapping, :run]
  before_action :authorize_user_import

  helper :users
  helper :issues
  helper :queries
  helper :imports

  def new
  end

  def index
    @imports = UserImport.order('created_at desc')
  end

  def create
    @import = UserImport.new
    @import.user = User.current
    @import.file = params[:file]
    @import.set_default_settings

    if @import.save
      redirect_to user_import_settings_path(@import)
    else
      render :action => 'new'
    end
  end

  def show
  end

  def settings
    if request.post? && @import.parse_file
      redirect_to user_import_mapping_path(@import)
    end

  rescue CSV::MalformedCSVError, ArgumentError, EncodingError => e
    if e.is_a?(CSV::MalformedCSVError) && e.message !~ /Invalid byte sequence/
      flash.now[:error] = l(:error_invalid_csv_file_or_settings)
    else
      flash.now[:error] = l(:error_invalid_file_encoding, :encoding => ERB::Util.h(@import.settings['encoding']))
    end
  rescue SystemCallError => e
    flash.now[:error] = l(:error_can_not_read_import_file)
  end

  def mapping
    if request.post?
      respond_to do |format|
        format.html {
          if params[:previous]
            redirect_to user_import_settings_path(@import)
          else
            redirect_to user_import_run_path(@import)
          end
        }
        format.js # updates mapping form on project or tracker change
      end
    end
  end

  def run
    if request.post?
      @current = @import.run(
          :max_items => max_items_per_request,
          :max_time => 10.seconds
      )
      respond_to do |format|
        create_memberships
        format.html {
          if @import.finished?
            redirect_to user_import_path(@import)
          else
            redirect_to user_import_run_path(@import)
          end
        }
        format.js
      end
    end
  end

  private

  def create_memberships
    return if @import.settings['memberships'].blank?

    projects = Project.where(id: @import.settings['memberships']['projects'])
    roles = Role.where(id: @import.settings['memberships']['roles'])
    functions = Function.where(id: @import.settings['memberships']['functions']) if Redmine::Plugin.installed?(:redmine_limited_visibility)

    if projects.present? && roles.present?

      if @import.finished?
        @import.saved_objects.each do |user|
          projects.each do |project|
            create_member_for_import_users(user, project, roles, functions)
          end
        end
      end
       # update the information of user who already existed
      @import.updated_users.each do |user|
        projects.each do |project|
          # check if member is exist
          member_found = Member.where(user: user, project: project)
          if member_found.empty?
            create_member_for_import_users(user, project, roles, functions)
           else
            member = member_found.first
            update_member_for_import_users(member, user, project, roles, functions)
          end
        end
      end
    end
  end

  def find_import
    @import = UserImport.where(:filename => params[:id]).first
    if @import.nil?
      render_404
      return
    elsif @import.finished? && action_name != 'show'
      redirect_to user_import_path(@import)
      return
    end
    update_from_params if request.post?
  end

  def update_from_params
    if params[:import_settings].present?
      @import.settings ||= {}
      @import.settings.merge!(params[:import_settings].to_unsafe_hash)
      @import.save!
    end
  end

  def max_items_per_request
    5
  end

  def create_member_for_import_users(user, project, roles, functions = nil)
    member = Member.new(user: user, project: project)
    member.roles = roles
    member.functions = functions if functions.present?
    member.save
    add_member_creation_to_journal(member, roles.pluck(:id), functions.pluck(:id)) if Redmine::Plugin.installed?(:redmine_admin_activity)
  end

  def update_member_for_import_users(member, user, project, roles, functions = nil)
    previous_role_ids = member.role_ids
    previous_function_ids = member.function_ids if Redmine::Plugin.installed?(:redmine_limited_visibility)
    member.roles<<(roles - member.roles)
    member.functions<<(functions - member.functions) if functions.present?
    member.save
    
    if Redmine::Plugin.installed?(:redmine_admin_activity)          
      unless (previous_role_ids.sort == member.roles.pluck(:id).sort && previous_function_ids.sort == member.functions.pluck(:id).sort)        
        add_member_edition_to_journal(member, previous_role_ids, member.roles.pluck(:id), previous_function_ids, member.functions.pluck(:id))
      end
    end
  end

  def authorize_user_import    
    return render_403 unless UserImport.authorized?(User.current)
  end

end

app/views/imports/_fields_memberships.html.erb
<p>
  <label for="import_mapping_projects"><%= l(:label_project_plural) %></label>
  <% if User.current.admin?%>
    <%= select_tag "import_settings[memberships][projects]", project_tree_options_for_select(Project.active.sorted), multiple: true %>
  <% else %>
    <%= select_tag "import_settings[memberships][projects]", project_tree_options_for_select(Project.all_public.active.sorted), multiple: true %>
  <% end %>
</p>

<p>
  <label for="import_mapping_roles"><%= l(:label_technical_role_plural) %></label>
  <%= select_tag "import_settings[memberships][roles]", options_from_collection_for_select(Role.givable.sorted, "id", "name"), multiple: true %>
</p>

<% if Redmine::Plugin.installed?(:redmine_limited_visibility) %>
  <p>
    <label for="import_mapping_functions"><%= l(:label_functional_roles) %></label>
    <%= select_tag "import_settings[memberships][functions]", options_from_collection_for_select(Function.sorted, "id", "name"), multiple: true %>
  </p>
<% end %>

<%= javascript_tag do %>
  if ((typeof $().select2) === 'function') {
  $('#import_settings_memberships_projects').select2();
  $('#import_settings_memberships_roles').select2();
  $('#import_settings_memberships_functions').select2();
  }
<% end %>

app/views/imports/index.html.erb
<div class="contextual">
  <%= link_to l(:label_new_csv_import), new_user_imports_path %>
</div>
<h2><%= l(:label_user_imports) %></h2>

<% if @imports.present? %>
  <table class="list imports">
    <thead>
    <th>Id</th>
    <th>Filename</th>
    <th>User</th>
    <th>Settings</th>
    <th>Mapping</th>
    <th>Memberships</th>
    <th>Saved items / Total items</th>
    <th>Finished</th>
    <th>Created_at</th>
    <th>Updated_at</th>
    </thead>
    <% @imports.each do |import| %>
      <tr>
        <td class="import"><%= link_to import.id, import_path(import) %></td>
        <td class="import"><%= link_to import.filename, import_path(import) %></td>
        <td class="import"><%= import.user %></td>
        <td class="import"><%= import.settings.reject { |k, v| k == 'mapping' || k == 'memberships' } %></td>
        <td class="import"><%= import.settings['mapping'] %></td>
        <td class="import"><%= import.settings['memberships'] %></td>
        <td class="import"><%= "#{import.saved_items.size} / #{import.total_items}" %></td>
        <td class="import"><%= import.finished %></td>
        <td class="import"><%= import.created_at %></td>
        <td class="import"><%= import.updated_at %></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/user_imports/index.html.erb
<div class="contextual">
  <%= link_to l(:label_new_csv_import), new_user_imports_path %>
</div>
<h2><%= l(:label_user_imports) %></h2>

<% if @imports.present? %>
  <table class="list imports">
    <thead>
    <th>Id</th>
    <th>Filename</th>
    <th>User</th>
    <th>Settings</th>
    <th>Mapping</th>
    <th>Memberships</th>
    <th>Saved items / Total items</th>
    <th>Finished</th>
    <th>Created_at</th>
    <th>Updated_at</th>
    </thead>
    <% @imports.each do |import| %>
      <tr>
        <td class="import"><%= link_to import.id, user_import_path(import) %></td>
        <td class="import"><%= link_to import.filename, user_import_path(import) %></td>
        <td class="import"><%= import.user %></td>
        <td class="import"><%= import.settings.reject { |k, v| k == 'mapping' || k == 'memberships' } %></td>
        <td class="import"><%= import.settings['mapping'] %></td>
        <td class="import"><%= import.settings['memberships'] %></td>
        <td class="import"><%= "#{import.saved_items.size} / #{import.total_items}" %></td>
        <td class="import"><%= import.finished %></td>
        <td class="import"><%= import.created_at %></td>
        <td class="import"><%= import.updated_at %></td>
      </tr>
    <% end %>
  </table>
<% end %>